import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';
// import { Toaster } from 'sonner';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Manga Admin',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en" className="light">
      <body className={inter.className}>
        <Providers>
          {/* <Toaster> */}
          {children}
          {/* </Toaster> */}
        </Providers>
      </body>
    </html>
  );
}
